---
title: "ISCO code"
author: "Emily Nussdorfer"
date: "2026-07-01"
---

Known time samples: Run code as usual

Unknown time samples: Run sections 1-4. After getting times, come back to section 5 and follow the instructions

## **Section 1- include sample information ([editable]{.underline}):**

Sample information 
```{r}
study <- "SSEMG" #the study code
samp_type <- "IS" #"IS" = ISCO
rn <- 1 #the start of a random number sequence. May change with projects or studies

```

```{r}
site <- c("STA","COA") #sites as a vector
nsamp <- c(24,24) #amount of samples per site. Matches the site vector above.
interval <- c(2,2) #interval of sampling ISCO is programmed for, usually 2hrs
blanktime <- "____________" # either have it blank  "____________" or with sampling date "YYYYMMDD____" or "YYYYMM______", etc
sc <- "20260223" #what sample campaign this is, the date it starts "YYYYMMDD" or something like sample_campaign-#. This is for file name purposes and doesn't effect sample naming
```


Analytes. Fill in TRUE or FALSE
```{r}
DOC <- TRUE
DOM <- TRUE
CCAL <- TRUE
Levoglucosan <- TRUE
Excess <- TRUE
```



```{r}
#optional change:
#can add a folder here if desired
#what format the files will end with. ex this returns: study_sapmpletype_date_label-table 
fileformat <- paste0(study,"_",samp_type,"_",sc,"_label-table.xlsx") #the file name
blank_fileformat <- paste0("blank_",study,"_",samp_type,"_",sc,"_label-table.csv") 
 
# field_blank <- TRUE
# lab_blank <- TRUE
nFB <- 1
nLB <- 1
blk <-c(nFB,nLB)


blanks <- data.frame(
  site=c("FB","LB")
)

blanks



```


```{r}
sn <- sum(nsamp) #total sample amount from the vector that was filled out
#adding sample information

pt2 <- FALSE

#sampleinfo <- data.frame(site=site,nsamp=nsamp,interval=interval,study=study,samp_type=samp_type,blanktime=blanktime, sn=sn, rn=rn)
#function
```




## **Section 2- run libraries:**

```{r libraries, include=FALSE}
library(dplyr)
library(stringr)
library(lubridate)
library(writexl)
source("helper_unknown.R")
```


```{r}


#if BLANKS == TRUE
#function 1  
data_label <- function(){
  sampleinfo <- data.frame(site=site,nsamp=nsamp,interval=interval,study=study,samp_type=samp_type,blanktime=blanktime, sn=sn, rn=rn)
  data_info <- function(sampleinfo){ #this function creates 
    return(data.frame(
      site =rep(sampleinfo$site, times = sampleinfo$nsamp),
      blank_time=sampleinfo$blanktime,
      botnum = sprintf("%02d",rep(1:24, times= ceiling(sampleinfo$nsamp/24))[1:sampleinfo$nsamp]),
      study=sampleinfo$study,samp_type=sampleinfo$samp_type
    ))}
  x<-lapply(1:nrow(sampleinfo),function(x){data_info(sampleinfo[x,])})%>%
    bind_rows()%>%
    mutate(
      randomn=sample(rn:sn,sn, replace=F),
      sample_name = paste0(study, "_", "R", sprintf("%04d",randomn)),
      field_sample_ID_blank= paste0(study, "_", site, "_", samp_type,"_",blanktime))
}







# lab_blank <- TRUE
nFB <- 1
nLB <- 1
blk <-c(nFB,nLB)
bn <- sum(nFB,nLB)
ts <- sum(sn,bn)

#somehow append this shit 
blanks <- data.frame(
  site=c("FB","LB"),
  blank_time = c("____________","____________"),
  type= c("BLK","BLK"))

blanks




```


```{r part 1 of code}

#main file
data_table<-data_label()

```




```{r}
#this prints your data labels out if you have blank samples, since you will need to rerun this code again.
safe.write_csv(data_table,
                 path = blank_fileformat,
                 row.names = FALSE)
stop("DO NOT CONTINUE UNTIL YOU HAVE YOUR TIMES. SAVE YOUR CODE") #ad to function

```



#code

```{r pt 5: and run, include=FALSE}
#enter the known start times on the ISCO (look at section 1 to match it to the correct site order)
start <- c("2026-02-23 15:00","2026-02-23 17:00")
pt2 <- TRUE
```

-   Run code below:

```{r pt 5: just run it, include=FALSE}

    
data_lab<-lab_label()



```


## Section 7- printing:

```{r warning=TRUE}









# write_data.frames <- list(
#   # field_labels = data_labels %>% select(sample_name,field_sample_ID,botnum),
#   lab_labels   = lab_data %>% select(sample_name,lab_sample_ID,analysis),
#   lab_filter_sheets = data_labels[order(data_labels$randomn),] %>% select(sample_name,field_sample_ID),
#   label_metadata = data_labels %>% select(site,datetime_PST,study,samp_type,randomn,botnum) #could delete this one
# )
# safe.write_xlsx(write_data.frames,
#                 path = fileformat)
```
