---
title: ""
geometry: margin=0.5in
output:
  pdf_document: default
  header-includes:
    - \usepackage{pdflscape}
    - \newcommand{\blandscape}{\begin{landscape}}
    - \newcommand{\elandscape}{\end{landscape}}
---

```{r libraries,include=FALSE}
library(dplyr)
library(stringr)
library(kableExtra)
library(readxl)
```

```{r import data, include=FALSE}
datasheet <- "SSEMG_IS_20260223_label-table.xlsx" #fill in
#delete the bot_num??? Keep for bottle weight??
```

```{r datasheets,include=FALSE}
#change columns if needed

#for note sheets
labsheet <- read_excel(datasheet, sheet ="lab_filter_sheets")
labsheet
#for ISCO weights
bottle_weights <- mutate(labsheet,pre_weight="", post_weight="",notes="")
bottle_weights
#for filtering
sample_bottles <- mutate(labsheet, Aqualog = "",Shimadzu = "", CCAL ="",Levoglucosan="",Excess="",notes="") #not sure how to do automatically without something janky
sample_bottles
#for filtering 
filter_weights <- mutate(labsheet,pre_weight="", post_weight="",notes="")
  # subset(labsheet, select = -botnum)%>%
  # mutate(pre_weight="", post_weight="",notes="")
filter_weights


```

# **Sample Bottle weights**

\pagestyle{empty}

Date: \_\_\_\_\_\_\_\_\_\_\_\_\_

Technician(s): \_\_\_\_\_\_\_\_\_\_\_\_\_\_


```{r bottle weights, echo=FALSE}
#knitr::kable(bottle_weights,booktabs=TRUE, vline = "|",linesep = '') #this does NOTHING. Wanted to add vertical lines and get rid of the line breaks every 5 rows
kable(bottle_weights,booktabs=FALSE) %>%
  kable_styling(latex_options = c("striped","hold_position","repeat_header"),
                full_width = FALSE,
                font_size = 10) %>%
  row_spec(0, bold = TRUE, color = "black", background = "#FFF7B0") %>%
  column_spec(1:ncol(bottle_weights),border_left = T)  %>% #adding vertical lines
  column_spec(ncol(bottle_weights), width= "15em",border_left = T, border_right = T)#widen the last row (notes) and add a vertical line 
  
 

```


\newpage

\blandscape
\pagestyle{empty}

# **Sample Bottle numbers**

Date: \_\_\_\_\_\_\_\_\_\_\_\_\_

Technician(s): \_\_\_\_\_\_\_\_\_\_\_\_\_\_

```{r sample bottle numbers, echo=FALSE}
kable(sample_bottles,booktabs=FALSE) %>%
  kable_styling(latex_options = c("striped", "hold_position","repeat_header"),
                full_width = FALSE,
                font_size = 10) %>%
   row_spec(0, bold = TRUE, color = "black", background = "#CDFFB0") %>%
  column_spec(ncol(sample_bottles), width= "15em") 
 
 


```

\elandscape

\newpage
\pagestyle{empty}

# Filter weights (filtering notes)

Date: \_\_\_\_\_\_\_\_\_\_\_\_\_

Technician(s): \_\_\_\_\_\_\_\_\_\_\_\_\_\_

```{r filter weights, echo=FALSE}
kable(filter_weights,booktabs=FALSE) %>%
  kable_styling(latex_options = c("striped", "hold_position","repeat_header"), 
                full_width = FALSE, 
                font_size = 10) %>%
  row_spec(0, bold = TRUE, color = "black", background = "#B0EEFF")%>%
  column_spec(ncol(filter_weights), width= "15em")

```
